// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38nwXxG83myq2MWUpgWrCriALtNVuU5w',
    appId: '1:782618690885:web:a2c8e7469a89da22046a2c',
    messagingSenderId: '782618690885',
    projectId: 'gridguardian-e7717',
    authDomain: 'gridguardian-e7717.firebaseapp.com',
    storageBucket: 'gridguardian-e7717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl3BcxqhuWQonbFSvXbh3qJlT0pCh4WQk',
    appId: '1:782618690885:android:f1405aef32ce1f16046a2c',
    messagingSenderId: '782618690885',
    projectId: 'gridguardian-e7717',
    storageBucket: 'gridguardian-e7717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BL4ECiqjiE90OQoEMGXP95v9eRT2lls',
    appId: '1:782618690885:ios:7afa44cc8cccb3b0046a2c',
    messagingSenderId: '782618690885',
    projectId: 'gridguardian-e7717',
    storageBucket: 'gridguardian-e7717.firebasestorage.app',
    iosBundleId: 'com.example.gridguardian',
  );
}
